name: sonar_analysis
description: >
  Sonar Dart lint rules.
version: 3.0.0
repository: https://github.com/4rthurmonteiro/sonar_analysis
issue_tracker: https://github.com/4rthurmonteiro/sonar_analysis/issues

environment:
  sdk: ^3.7.2

dependencies:
  flutter_lints: ^6.0.0

topics:
  - analysis
  - lints
  - sonar

